server:
  port: 8888
spring:
  application:
    name: web
  config:
    import: optional:configserver:http://localhost:8080
management:
  endpoints:
    web:
      exposure:
        include: 'refresh'
